package app.opentasks.core.sync

object CloudBounds {
    const val MAX_HEADER_BYTES = 16 * 1024
    const val MAX_MANIFEST_CIPHERTEXT_BYTES = 1L * 1024 * 1024
    const val MAX_SNAPSHOT_CIPHERTEXT_BYTES = 64L * 1024 * 1024
    const val MAX_OPERATION_SEGMENT_CIPHERTEXT_BYTES = 16L * 1024 * 1024
    const val MAX_ATTACHMENT_CHUNK_PLAINTEXT_BYTES = 4L * 1024 * 1024
    const val AES_GCM_V1_CIPHERTEXT_OVERHEAD_BYTES = 33L
    const val MAX_ATTACHMENT_CHUNK_CIPHERTEXT_BYTES_V1 =
        MAX_ATTACHMENT_CHUNK_PLAINTEXT_BYTES + AES_GCM_V1_CIPHERTEXT_OVERHEAD_BYTES
    const val MAX_ATTACHMENT_CHUNKS = 26
    const val MAX_OPERATIONS_PER_SEGMENT = 10_000
    const val MAX_RECORDS_PER_SNAPSHOT = 100_000
    const val MAX_MANIFEST_INVENTORY_ENTRIES = 10_000

    internal fun maximumCiphertextBytes(family: CloudObjectFamily): Long = when (family) {
        CloudObjectFamily.MANIFEST -> MAX_MANIFEST_CIPHERTEXT_BYTES
        CloudObjectFamily.SNAPSHOT -> MAX_SNAPSHOT_CIPHERTEXT_BYTES
        CloudObjectFamily.OPERATION_SEGMENT -> MAX_OPERATION_SEGMENT_CIPHERTEXT_BYTES
        CloudObjectFamily.ATTACHMENT_CHUNK ->
            MAX_ATTACHMENT_CHUNK_CIPHERTEXT_BYTES_V1
    }
}
